const hre = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
    console.log("Deploying EduFund...");

    const [deployer] = await hre.ethers.getSigners();
    console.log("Account:", deployer.address);

    const balance = await hre.ethers.provider.getBalance(deployer.address);
    console.log("  Account balance:", hre.ethers.formatEther(balance), "ETH");

    // Deploy EduToken
    const EduToken = await hre.ethers.getContractFactory("EduToken");
    const eduToken = await EduToken.deploy(deployer.address);
    await eduToken.waitForDeployment();

    const eduTokenAddress = await eduToken.getAddress();
    console.log("EduToken:", await eduToken.getAddress());

    // Deploy EduFund
    const EduFund = await hre.ethers.getContractFactory("EduFund");
    const eduFund = await EduFund.deploy(eduTokenAddress);
    await eduFund.waitForDeployment();

    const eduFundAddress = await eduFund.getAddress();
    console.log("EduFund:", await eduFund.getAddress());

    // Transfer Ownership
    await eduToken.transferOwnership(await eduFund.getAddress());
    console.log("Ownership transferred");

    if (newOwner.toLowerCase() === eduFundAddress.toLowerCase()) {
        console.log("   ✓ Verified: EduFund can now mint EDU tokens");
    } else {
        console.error("   ✗ ERROR: Ownership transfer failed!");
        process.exit(1);
    }

    // save Artifacts

    const frontendDir = path.join(__dirname, "..", "frontend", "src", "contracts");

    // create contracts directory if it doesn't exist
    if (!fs.existsSync(frontendDir)) {
        fs.mkdirSync(frontendDir, { recursive: true });
    }

    // get ABIs from artifacts
    const eduTokenArtifact = await hre.artifacts.readArtifact("EduToken");
    const eduFundArtifact = await hre.artifacts.readArtifact("EduFund");

    // create deployment info object
    const deploymentInfo = {
        network: hre.network.name,
        chainId: hre.network.config.chainId || 31337,
        deployer: deployer.address,
        timestamp: new Date().toISOString(),
        contracts: {
            EduToken: {
                address: eduTokenAddress,
                abi: eduTokenArtifact.abi
            },
            EduFund: {
                address: eduFundAddress,
                abi: eduFundArtifact.abi
            }
        }
    };

    // save to frontend
    const deploymentPath = path.join(frontendDir, "deployment.json");
    fs.writeFileSync(deploymentPath, JSON.stringify(deploymentInfo, null, 2));
    console.log(" Deployment info saved to:", deploymentPath);

    // Also save individual contract files for easier imports
    fs.writeFileSync(
        path.join(frontendDir, "EduToken.json"),
        JSON.stringify({ address: eduTokenAddress, abi: eduTokenArtifact.abi }, null, 2)
    );
    fs.writeFileSync(
        path.join(frontendDir, "EduFund.json"),
        JSON.stringify({ address: eduFundAddress, abi: eduFundArtifact.abi }, null, 2)
    );
    fs.writeFileSync(
        path.join(frontendDir, "EduFund.json"),
        JSON.stringify({ address: eduFundAddress, abi: eduFundArtifact.abi }, null, 2)
    );
    console.log(" Individual contract files saved");

    // save Config
    const configPath = path.join(__dirname, "..", "frontend", "config.js");
    const configContent = `
// Auto-generated by scripts/deploy.js
const CONTRACT_CONFIG = {
    EDUFUND_ADDRESS: "${eduFundAddress}",
    EDUTOKEN_ADDRESS: "${eduTokenAddress}",
    EDUFUND_ABI: ${JSON.stringify(eduFundArtifact.abi)},
    EDUTOKEN_ABI: ${JSON.stringify(eduTokenArtifact.abi)}
};
    `.trim();

    fs.writeFileSync(configPath, configContent);
    console.log(" config.js generated at:", configPath);

    console.log("Config generated");
    console.log("Deployment complete.");

    return { eduToken, eduFund, eduTokenAddress, eduFundAddress };
}

main()
    .then(() => process.exit(0))
    .catch((error) => {
        console.error("\n  Deployment failed!");
        console.error(error);
        process.exit(1);
    });
